<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        body { font-family: 'Helvetica', sans-serif; padding: 20px; color: #333; line-height: 1.5; }
        .header { border-bottom: 2pt solid #0d6efd; padding-bottom: 10px; margin-bottom: 20px; }
        .ngo-name { font-size: 22pt; font-weight: bold; color: #0d6efd; }
        .report-title { font-size: 16pt; font-weight: bold; color: #555; }
        .meta { font-size: 9pt; color: #777; margin-top: 5px; }
        
        .section-title { font-size: 14pt; font-weight: bold; margin: 20px 0 10px; padding-bottom: 5px; border-bottom: 1pt solid #eee; color: #0d6efd; }
        
        .stats-grid { width: 100%; margin-bottom: 20px; }
        .stat-box { background: #f8f9fa; padding: 15px; border-radius: 8px; border: 1pt solid #eee; text-align: center; }
        .stat-label { font-size: 8pt; text-transform: uppercase; color: #666; font-weight: bold; }
        .stat-value { font-size: 18pt; font-weight: bold; color: #000; }
        
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background-color: #f2f2f2; padding: 8px; text-align: left; font-size: 10pt; border: 1pt solid #ddd; }
        td { padding: 8px; text-align: left; font-size: 9pt; border: 1pt solid #ddd; }
        
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 8pt; color: #999; border-top: 1pt solid #eee; padding-top: 5px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="ngo-name">{{ $siteSettings['site_name'] ?? 'Smart NGO' }}</div>
        <div class="report-title">Performance Summary Report</div>
        <div class="meta">Generated by Admin on {{ $generated_at }}</div>
    </div>

    <div class="section-title">Key Performance Indicators</div>
    <table class="stats-grid">
        <tr>
            <td width="25%">
                <div class="stat-box">
                    <div class="stat-label">Total Members</div>
                    <div class="stat-value">{{ number_format($stats['total_members']) }}</div>
                </div>
            </td>
            <td width="25%">
                <div class="stat-box">
                    <div class="stat-label">Total Donations</div>
                    <div class="stat-value">₹{{ number_format($stats['total_donations'], 2) }}</div>
                </div>
            </td>
            <td width="25%">
                <div class="stat-box">
                    <div class="stat-label">Active Campaigns</div>
                    <div class="stat-value">{{ number_format($stats['total_campaigns']) }}</div>
                </div>
            </td>
            <td width="25%">
                <div class="stat-box">
                    <div class="stat-label">Pending Enquiries</div>
                    <div class="stat-value">{{ number_format($stats['pending_enquiries']) }}</div>
                </div>
            </td>
        </tr>
    </table>

    <div class="section-title">Recent Successful Donations</div>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Donor Name</th>
                <th>Email</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($stats['recent_donations'] as $donation)
            <tr>
                <td>{{ $donation->created_at->format('d M, Y') }}</td>
                <td>{{ $donation->name ?? $donation->user->name ?? 'Anonymous' }}</td>
                <td>{{ $donation->email ?? $donation->user->email ?? 'N/A' }}</td>
                <td><strong>₹{{ number_format($donation->amount, 2) }}</strong></td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="section-title">Top Referral Members</div>
    <table>
        <thead>
            <tr>
                <th>Member Name</th>
                <th>Email</th>
                <th>Joined Date</th>
                <th>Referrals</th>
            </tr>
        </thead>
        <tbody>
            @foreach($stats['top_members'] as $member)
            <tr>
                <td>{{ $member->name }}</td>
                <td>{{ $member->email }}</td>
                <td>{{ $member->created_at->format('d M, Y') }}</td>
                <td align="center"><strong>{{ $member->referrals_count }}</strong></td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        © {{ date('Y') }} {{ $siteSettings['site_name'] ?? 'Smart NGO' }}. This is a confidential performance report for internal use only.
    </div>
</body>
</html>
